Users/urls.py
from django.urls import path, include
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path('home/',views.index,name='index'),
    path('profile/<str:username>',views.profile,name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('signup/',views.signup,name='signup'),
    path('search/',views.search,name='search'),
    path('autocomplete/',views.autocomplete,name='autocomplete'),
    path('terms_and_conditions/',views.terms,name='terms'),
    path('',RedirectView.as_view(url='home/'))
]

announcements/urls.py
# announcements/urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('', views.announcements_view, name='announcements'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Adding new urlpatterns
    path('helper/',include('helper.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('surveys/', include('surveys.urls')),
    path("notify/",include('notifications_app.urls')),
    path("verify/", include('verification_app.urls')),
    path('announcements/', include('announcements.urls')),

    path('',include('Users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.core.validators import RegexValidator, MaxLengthValidator, FileExtensionValidator
from mysite.constants import JNV_MAP_LIST, STATES
from django.contrib.auth.models import User
from notifications_app.models import Notification, BroadcastNotification

# Create your models here.
class UserCard(models.Model):
    class RegionName(models.TextChoices):
        BHOPAL = 'BP',_('Bhopal')
        CHANDIGARH = 'CH',_('Chandigarh')
        HYDERABAD = 'HB',_('Hyderabad')
        JAIPUR = 'JP',_('Jaipur')
        LUCKNOW = 'LK',_('Lucknow')
        PATNA = 'PT',_('Patna')
        PUNE = 'PN',_('Pune')
        SHILLONG = 'SH',_('Shillong')
    
    ROLE_CHOICES = (
        ('T', 'Teacher'),
        ('A', 'Alumnus/Alumna'),
        ('W', 'Worker'),
        ('S', 'Student'),
        ('O', 'Office Member'),
    )
    
    
    default_region_name = "JP" # default 
    
    user = models.OneToOneField(User, on_delete=models.RESTRICT, primary_key=True)
    region_name = models.CharField(max_length =2, choices=RegionName.choices)
    jnv_name = models.CharField(max_length = 50,choices=[(w,"Jawahar Navodaya Vidyalaya, "+w) for y in JNV_MAP_LIST.values() for w in y])
    
    verified = models.BooleanField(default=False)
    role = models.CharField(max_length=1,choices=ROLE_CHOICES)
    year = models.PositiveIntegerField(blank=True,null=True)
    HomeTown = models.CharField(max_length=300,blank=True,null=True)
    profile_photo = models.ImageField(
        upload_to='profile_photos/',
        default='default_profile.png',
        validators=[
            MaxLengthValidator(limit_value=100 * 1024, message="The image size should be less than 100KB."),
            FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'], message="Only PNG and JPG files are allowed."),
            # ... Other validators if needed ...
        ]
    )
    def __str__(self) -> str:
        return "Public Data User:"+self.user.username
    
class UserPrivateInfo(models.Model):
    
    user = models.OneToOneField(User, on_delete=models.RESTRICT, primary_key=True)
    current_location_city = models.CharField(max_length=300,blank=True,null=True)
    current_location_state = models.CharField(max_length=40,choices =[(x,x) for x in STATES],blank=True,null=True)
    current_location_zip = models.PositiveIntegerField(blank=True,null=True)
    profession = models.CharField(max_length=60,blank=True,null=True)
    
    @property
    def unread_notification(self):
        # Get unread notifications for the specific user
        unread_notifications = Notification.objects.filter(user=self.user, read=False)[:5]
        
        # Get broadcast notifications
        broadcast_notifications = BroadcastNotification.objects.all()[:5]
        
        # Combine the two sets of notifications
        all_notifications = list(unread_notifications) + list(broadcast_notifications)
        
        # Sort the combined notifications by timestamp
        all_notifications.sort(key=lambda notification: notification.timestamp if isinstance(notification, Notification) else notification.broadcast_on, reverse=True)
        
        # Get the count of unread notifications
        unread_count = Notification.objects.filter(user=self.user, read=False).count()
        
        return {
            'count': unread_count,
            'notifications': all_notifications
        }
    
    def __str__(self) -> str:
        return "Private Data User:"+self.user.username

announcements/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class AnnouncementGroup(models.Model):
    name = models.CharField(max_length=100)
    administrators = models.ManyToManyField(User, related_name='admin_groups')
    
class Announcement(models.Model):
    group = models.ForeignKey(AnnouncementGroup, on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.RESTRICT)
    read_by = models.ManyToManyField(User, related_name='read_announcements')
    

announcements/views.py
# announcements/views.py

from django.http import JsonResponse
from django.shortcuts import render
from .models import AnnouncementGroup, Announcement
from Users.decorators import verified_user_required

@verified_user_required
def announcements_view(request):
    group_names = []
    jnv_group_name = f"jnv_{request.user.usercard.jnv_name}".replace(' ','_')
    region_group_name = f"region_{request.user.usercard.region_name}".replace(' ','_')
    group_names.extend(['All',jnv_group_name,region_group_name])
    if request.user.usercard.role=='S' or request.user.usercard.role=='A':
        group_names.append(f"Batch_{request.user.usercard.jnv_name}_{request.user.usercard.year}".replace(' ','_'))
    
    group_list = []
    for group in group_names:
        group,created = AnnouncementGroup.objects.get_or_create(name=group)
        if group:
            group_list.append(group)
    
    chat = {}
    for group in group_list:
        obj = Announcement.objects.filter(group=group).order_by('timestamp')
        chat[group] = obj
    
    context = {'groups': group_list, 'chat': chat}
    return render(request, 'announcements.html', context)

templates/announcements.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid h-100">
    <div class="row h-100">
        <div class="col-md-4 bg-light border-right">
            <nav class="navbar navbar-light bg-light justify-content-between">
                <a class="navbar-brand">Announcement Groups</a>
                <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
            </nav>
            <ul class="list-group list-group-flush mt-3">
                {% for group in groups %}
                <li class="list-group-item list-group-item-action group-item" data-group="{{ group.name }}">
                    {{ group.name }}
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-md-8">
            <div class="chat-container d-flex flex-column vh-100 overflow-hidden">
                {% for group,all_messages in chat.items %}
                <div class="d-none chat-messages flex-grow-1 p-4 overflow-auto" id="{{group.name}}-chat-messages">
                    {% for msg in all_messages %}
                    <div class="chat-bubble">
                        <div class="sender-username">
                            <a href="{% url 'profile' msg.created_by.username%}" class="profile-link" target="_blank">{{msg.created_by.username}}</a>
                        </div>
                        {{msg.content}}
                        <div class="message-info">
                            {{msg.timestamp}}
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}
                <div class="chat-messages flex-grow-1 p-4 overflow-auto" id="null-chat-messages">
                    <h5 class="text-center mt-4">Choose Any One Group.</h5>
                </div>
                <div class="chat-input p-3 border-top">
                    <form id="message-form">
                        <div class="input-group">
                            <textarea id="message-input" class="form-control" placeholder="Type your message..." disabled></textarea>
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-primary mx-2 my-2">Send</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
document.addEventListener("DOMContentLoaded", () => {
    // WebSocket connection
    const socket = new WebSocket('ws://' + window.location.host + '/ws/announcements/');
    let selectedGroup = null;
    const is_admin = {
        {% for group in groups %}
            "{{ group.name }}": {% if request.user in group.administrators.all %}true{% else %}false{% endif %},
        {% endfor %}
    };

    socket.onmessage = (event) => {
        const data = JSON.parse(event.data);
        const sender = data.sender;
        const message = data.announcement;
        const timestamp = data.timestamp;
        const group = data.group;

        // Display the incoming message
        const chatMessages = document.getElementById(group+'-chat-messages');
        const newMessage = document.createElement('div');
        newMessage.className = 'chat-bubble';
        newMessage.innerHTML = `<div class="sender-username">
            <a href="/profile/${sender}" class="profile-link" target="_blank">${sender}</a>
        </div>${message}<div class="message-info">${timestamp}</div>`;
        chatMessages.appendChild(newMessage);

        // Scroll to the bottom of the chat container to show the latest message
        chatMessages.scrollTop = chatMessages.scrollHeight;
    };

    // Handle form submission to send messages
    const messageForm = document.getElementById('message-form');
    messageForm.addEventListener('submit', (event) => {
        event.preventDefault();
        const messageInput = document.getElementById('message-input');
        if (messageInput.value && selectedGroup) {
            // Send the message to the WebSocket server
            socket.send(JSON.stringify({
                message: messageInput.value,
                group: selectedGroup,
            }));

            // Clear the input field
            messageInput.value = '';
        }
    });

    // Highlight selected group and load messages
    const listGroupItems = document.querySelectorAll('.list-group-item');
    let previousGroup = 'null';
    listGroupItems.forEach((item) => {
        item.addEventListener('click', () => {
            listGroupItems.forEach((otherItem) => {
                otherItem.classList.remove('active');
            });
            item.classList.add('active');
            selectedGroup = item.getAttribute('data-group');
            if (selectedGroup!=previousGroup){
                const prev = document.getElementById(previousGroup+'-chat-messages');
                prev.classList.add('d-none');
                const now = document.getElementById(selectedGroup+'-chat-messages');
                now.classList.remove('d-none');
                const submit_text = document.getElementById('message-input');
                submit_text.disabled = !is_admin[selectedGroup]
                previousGroup = selectedGroup;
            }
        });
    });
});
</script>
<style>
    .chat-bubble {
        max-width: 80%;
        padding: 10px;
        margin: 10px 0;
        border-radius: 15px;
        background-color: #DCF8C6;
    }
    
    /* Style for message info (timestamp or sender's name) */
    .message-info {
        font-size: 12px;
        color: #999;
        text-align: right;
        margin-top: 5px;
    }
    
    .sender-username {
        font-weight: bold;
    }
</style>
{% endblock %}

templates/apply_poc.html
{% extends "base.html" %}

{% block title %}Point of Contact (POC) Application{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="card shadow mx-auto" style="max-width: 600px;">
        <div class="card-body">
            <div class="text-center mb-4">
                <h4 class="card-title">Point of Contact (POC) Application</h4>
            </div>

            <!-- POC Application Form -->
            <div class="mb-4">
                <h5>Apply for Point of Contact (POC)</h5>
                <p>Upload documents which verify your JNV:</p>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="documents">Documents (TC, marksheet, character certificate, etc.):</label>
                        <input type="file" class="form-control" id="documents" name="documents" required>
                    </div>
                    <br>
                    <button type="submit" class="btn btn-primary">Submit Application</button>
                </form>
            </div>

            <!-- Responsibilities -->
            <div class="mb-4">
                <h5>Your Responsibilities as POC</h5>
                <p>By applying for POC, you agree to:</p>
                <ul>
                    <li>Have the power to add your batchmates to the website.</li>
                    <li>Be the admin of your batch group and represent your batch on the website.</li>
                </ul>
            </div>

            <!-- Note -->
            <div class="mb-4">
                <h5>Note</h5>
                <p>This is not an official website. We are collecting your documents to verify that you are a Navodayan.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
<!-- base.html -->
{% comment "block elements" %}
content: contains the body
title: title of the base file
{% endcomment %}

{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
    {% block title %}
    {% endblock title %}
  </title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand">Navodaya Network</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'helper' %}">Helper</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'search' %}">Advance Search</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'survey_list' %}">Surveys</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'verify' %}">Verification</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'announcements' %}">Announcements</a>
          </li>
        </ul>
        {% if user.is_authenticated %}
        <ul class="navbar-nav">
          <li class="nav-item">
        <form class="d-flex" role="search" action="{% url 'search' %}" method="GET">
          <input class="form-control me-2" type="search" placeholder="First Name of Person" aria-label="Search"
            name='fname'>
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        <li class="nav-item dropdown">
          <!-- Bell Icon Button with Notification Badge -->
          <button class="nav-link btn btn-link dropdown-toggle" type="button" id="notificationsDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-bell"></i>
              <span class="badge badge-pill badge-danger" id="notification-badge">{{ request.user.userprivateinfo.unread_notification.count }}</span>
          </button>
          <!-- Dropdown List for Notifications -->
          <div class="dropdown-menu dropdown-menu-right animate__animated animate__fadeIn" aria-labelledby="notificationsDropdown" id="notification-dropdown-items" style="max-height: 400px; overflow-y: auto;">
              <ul class="list-unstyled">
                  {% for notification in request.user.userprivateinfo.unread_notification.notifications %}
                  <li>
                      <a class="dropdown-item text-wrap" href="{% url 'notification' %}">{{ notification.message }}</a>
                  </li>
                  {% endfor %}
                  <li class="dropdown-divider"></li>
                  <li>
                      <a class="dropdown-item" href="{% url 'notification' %}">More ...</a>
                  </li>
              </ul>
          </div>
      </li>
      
      
    
    
      {{ room_name|json_script:"room-name" }}
      <li class="navbar-nav">
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {% if request.user.usercard.profile_photo %}
              <img src="{{ request.user.usercard.profile_photo.url }}" alt="{{ user.username }}" class="rounded-circle" width="30" height="30">
            {% else %}
              <i class="fas fa-user-circle fa-lg rounded-circle"></i>
            {% endif %}
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="profileDropdown">
            <li>
              <a class="dropdown-item" href="{% url 'profile' username=user.username %}">Profile</a>
            </li>
            <li>
              <form action="{% url 'logout' %}" method="GET">
                <button type="submit" class="dropdown-item">Logout</button>
              </form>
            </li>
          </ul>
        </div>
      </li>
      <ul>
        {% else %}

        <form class="d-flex" action="{% url 'login' %}" method="GET">
          <button type="submit" class="btn btn-primary">Login</button>
        </form>
        {% endif %}
      </div>
    </div>
  </nav>
  
  <div class="position-relative">
    {% if messages %}
    <div class="position-fixed top-0 end-0 mt-3" style="z-index:1;">
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong>Message:</strong> {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  
    <div class="position-relative">
      <div class="content">
        {% block content %}
        {% endblock content %}
      </div>
    </div>
  </div>
  
  

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
    crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
      // Initialize Bootstrap alert functionality
      var alertList = document.querySelectorAll('.alert')
      alertList.forEach(function (alert) {
        new bootstrap.Alert(alert)
      })
    });

    {% comment %} WebSocket code below {% endcomment %}

    const notificationSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/notification/'
        + 'broadcast'
        + '/'
    );

    const userNotifySocket = new WebSocket(
      'ws://'+ window.location.host + '/ws/user-notifications/'
    )
    notificationSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        //document.querySelector('#notification-log').value += (data.message + '\n');
        console.log(data)
        document.getElementById("notification-dropdown-items").innerHTML = "<a class='dropdown-item' href='#'>"+ data+"</a>"+document.getElementById("notification-dropdown-items").innerHTML;
        document.getElementById("notification-badge").innerHTML = parseInt(document.getElementById("notification-badge").innerHTML) + 1;
    };

    notificationSocket.onclose = function(e) {
        console.error('Notification socket closed unexpectedly');
    };

    userNotifySocket.onmessage = function(e) {
      const data = JSON.parse(e.data);
      //document.querySelector('#notification-log').value += (data.message + '\n');
      console.log(data)
      document.getElementById("notification-dropdown-items").innerHTML = "<a class='dropdown-item' href='#'>"+ data+"</a>"+document.getElementById("notification-dropdown-items").innerHTML;
      document.getElementById("notification-badge").innerHTML = parseInt(document.getElementById("notification-badge").innerHTML) + 1;
    };
    userNotifySocket.onclose = function(e) {
      console.error('User-Notification socket closed unexpectedly');
    };
</script>
</body>

</html>

templates/float_base.html
{% extends 'base.html' %}

{% block content %}
<!-- Section: Design Block -->
<section class="text-center">
    <!-- Background image -->
    <div class="p-5 bg-image" style="
          background-image: url('https://mdbootstrap.com/img/new/textures/full/171.jpg');
          height: 300px;
          "></div>
    <!-- Background image -->
  
    <div class="card mx-4 mx-md-5 shadow-5-strong" style="
          margin-top: -100px;
          background: hsla(0, 0%, 100%, 0.8);
          backdrop-filter: blur(30px);
          ">
      {% block float_content %}{% endblock float_content %}
    </div>
  </section>
  <!-- Section: Design Block -->
{% endblock%}

templates/profile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock title %}
{% block content %}
<section style="background-color: #f9f9f9;">
    <!-- Profile Card Section -->
    <div class="container py-3 ">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="card mb-4">
                    <div class="card-body text-center">
                        <div class="user-card">
                            <a href="#newModal" data-bs-toggle="modal">
                              <img src="{{ user_card.profile_photo.url }}" alt="{{ user.username }}" class="rounded-circle img-fluid" style="width: 150px;">
                            </a>
                          </div>
                          
                          <!-- Modal for the image -->
                          <div class="modal fade" id="newModal" tabindex="-1" aria-labelledby="profileModalLabel"
                          aria-hidden="true"role="dialog">
                            <div class="modal-dialog" role="document">
                              <div class="modal-content">
                                <div class="modal-header">
                                  <h5 class="modal-title">Full Size Picture</h5>
                                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                  <img src="{{ user_card.profile_photo.url }}" alt="{{ user.username }}" class="img-fluid">
                                </div>
                              </div>
                            </div>
                          </div>
                          
                        <h5 class="my-3">{{ user.get_full_name }}</h5>
                        {% if is_own_profile %}
                        <div class="d-flex justify-content-center mb-2">
                            <a href="{% url 'edit_profile' %}" class="btn btn-primary">Edit Profile</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
                <!-- Other Social Links, if any -->
            </div>

            <!-- Public Info Card Section -->
            <div class="col-lg-8">
                <div class="card mb-4">
                    <div class="card-header">
                        <h4>Public Info</h4>
                    </div>
                    <div class="card-body">
                        <!-- Other Public Info Details -->
                        <div class="row">
                            <div class="col-sm-3">
                                <strong>Full Name</strong>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{ user.get_full_name }}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <strong>Username</strong>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{ user.username }}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <strong>JNV Region</strong>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{ user_card.get_region_name_display }}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <strong>JNV Name</strong>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{ user_card.get_jnv_name_display }}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <strong>Role</strong>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{ user_card.get_role_display }}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <strong>Batch Year</strong>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{ user_card.year }}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <strong>Home Town</strong>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{ user_card.HomeTown }}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <strong>IS Verified</strong>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{ user_card.verified }}</p>
                            </div>
                        </div>
                        <hr>
                        
                        <!-- Add other public info details as needed -->
                    </div>
                </div>
            </div>

            <!-- Private Info Card Section -->
            {% if is_own_profile %}
            <div class="col-lg-8">
                <div class="card mb-4">
                    <div class="card-header">
                        <h4>Private Info</h4>
                    </div>
                    <div class="card-body">
                        <!-- Other Private Info Details -->
                        <div class="row">
                            <div class="col-sm-3">
                                <strong>Current Location City</strong>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{ user_private_info.current_location_city }}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <strong>Current Location State</strong>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{ user_private_info.current_location_state }}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <strong>Current Location Zip</strong>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{ user_private_info.current_location_zip }}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <strong>Current Profession</strong>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{ user_private_info.profession }}</p>
                            </div>
                        </div>
                        <!-- Add other private info details as needed -->
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}